[package]
name = "verbium_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
toml_edit = "0.22"
zip = "0.6"
walkdir = "2.5"
rfd = "0.14"
anyhow = "1.0"
serde_json = "1.0"
